Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,13 +16,13 @@ jobs:
         echo Downloading .NET Framework 4.7.2 installer...
         curl -L -o NDP472-DevPack-ENU.exe "https://drive.google.com/uc?export=download&id=1Az1a3KTD7kpKjce32tnouUum95WZVsKb"
 
-    - name: Verify Installer
+    - name: Verify Installer File
       run: |
         echo Verifying installer file...
         if (!(Test-Path .\NDP472-DevPack-ENU.exe)) {
-          Write-Error "Installer not found in the current directory!"
-          exit 1
-        }
+        Write-Error "Installer not found in the current directory!"
+        exit 1
+       }
         echo Installer file found.
 
     - name: Install .NET Framework 4.7.2
